### PR TITLE
updating About GeoBlacklight page

### PR DESCRIPTION
**Pull request by lenathelibrarian**
These are the proposed updates to the About GeoBlacklight page. Thanks!

### CODE REVIEW

**Review by mejackreed — APPROVED** [review]
👏 Thanks for this work!

**Review by karenmajewicz — CHANGES_REQUESTED** [review]
The bulleted list sorts of blurs into what was a navigation menu. Should we just remove the menu?
Screen Shot 2021-02-26 at 4 52 08 PM

**Comment by karenmajewicz** [comment]
Not sure if my text comment went through- I was thinking maybe we should just remove what had been a bulleted navigation/ table of contents?

**Comment by lenathelibrarian** [comment]
> Not sure if my text comment went through- I was thinking maybe we should just remove what had been a bulleted navigation/ table of contents? It doesn't really fit in where it is anymore.

Oops, didn't see that! I was thinking the same thing and forgot to do something about it, Karen. I'm happy for it to be changed.

**Pull request merged**
