### PR TITLE
add roles

### PR DESCRIPTION
**Pull request by karenmajewicz**
Here are a few screenshots of how it looks with the highlighting. Please suggest changes!

Screenshot 2024-04-09 at 12 11 30 PM
Screenshot 2024-04-09 at 12 11 45 PM
Screenshot 2024-04-09 at 12 11 54 PM

### CODE REVIEW

**Comment by rmseifried** [comment]
I'm not able to spin this up to test the changes I made - hopefully still looks the same! I made some minor editorial changes, and removed the number of people anticipated for each role, as it seems repetitive (the number of vacancies being highlighted).

One thought - perhaps the header could be "Community Roles" instead of simply "Roles"? Or something similar?

**Comment by rmseifried** [comment]
Another thought: this section seems related to "How to Contribute." Is there a way to synthesize them, or at least make it more obvious that people are invited to volunteer for these positions?

**Comment by karenmajewicz** [comment]
I rearranged the Community page to prioritize a "Join the Community" section at the top. I also moved "Our Development Practices" to the About page.

**Comment by karenmajewicz** [comment]
I am going to publish these changes so that we can look at them during the GBL meeting. We will of course make further changes - it doesn't say anything yet about how to volunteer for a role or join a workgroup.

**Pull request merged**
