### PR TITLE
Migrates wiki data to website for search engine indexing

### PR DESCRIPTION
**Pull request by sdellis**
ToDos: 

- Move the Table of Contents to a fixed column or use Scrollspy for improved navigation
- Create includes for each section to make updating the documentation easier

### CODE REVIEW

**Comment by eliotjordan** [comment]
@sdellis This looks very nice. Might be helpful to include a screen shot or two in the comments as an example.

**Comment by sdellis** [comment]
@eliotjordan good idea. Here's the current view with the TOC on the left. I'm going to tweak this a bit, but this is the idea.

Screen Shot 2022-02-18 at 9 22 42 AM

**Comment by sdellis** [comment]
For some reason Sass is not compiling on Jekyll for me. :(

**Comment by sdellis** [comment]
Final todo: It's not responsive on mobile yet. Content area should wrap below the TOC on smaller screens.

**Comment by reinacmurray** [comment]
The example screenshot under **Adding support for item images** is broken:
image

**Comment by reinacmurray** [comment]
I really like this guide! It's a lot cleaner than the wiki -- is the plan to consolidate the in-depth tutorials (which probably need to be updated) into this guide as well? The in-depth tutorials provide a lot more details on setting up environments, etc, which is helpful for beginners. It might be good to either integrate that in or to have language and a link to the tutorial, and note that this guide is targeted/aimed at developers.

**Comment by sdellis** [comment]
@reinacmurray good catch on the broken image. I fixed it and pushed the commit. 

As for the in-depth tutorials... I agree that they would be best integrated into the guides. These guides currently seem to have what it takes to start contributing (as a developer) on the GeoBlacklight app. The tutorials seem to teach you how to run your own customized instance of GeoBlacklight. It is not entirely clear to me whether you can simply customize GeoBlacklight from where the "Getting Started for Developers" section leaves you, or if you have to install it differently for that goal. I have been able to install from the instructions in the Guides (former wiki), but have not been able to get it running from the instructions in Tutorials.

**Comment by sdellis** [comment]
@karenmajewicz I've updated the code in this PR. My last commit fixes the sidebar overflow issue you reported today. It also updates the Upgrading to 4.0 guide with all of @ewlarson's recent changes.

**Comment by karenmajewicz** [comment]
Thanks - this is great. I made a ticket #166 that we might want to look into updating our template. To explore at a later date!

**Pull request merged**
